# Generated by Django 5.2.3 on 2025-06-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='aVjarUuFX9kxhACPfpuWie', max_length=128, unique=True),
        ),
    ]
