# Generated by Django 5.2.3 on 2025-07-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='F5kj3TySZ5j9ptLsGrA3pz', max_length=128, unique=True),
        ),
    ]
