# Generated by Django 5.2.3 on 2025-06-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='W2NywNob3zE6ZfrSpNiZ53', max_length=128, unique=True),
        ),
    ]
