# Generated by Django 5.2.3 on 2025-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0006_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='HoMdEsPR7quGL4bT4H4pKp', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
