# Generated by Django 5.2.3 on 2025-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0007_chatmessage_file_alter_chatgroup_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='WPrzgehVLKNzboDFANvRkE', max_length=128, unique=True),
        ),
    ]
